name: Deploy to Hashnode

on:
  pull_request:
    types: [closed]
    branches:
      - develop

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install

      - name: Run script the hashnode publisher script
        run: |
          node hashnode/scripts.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HASH_NODE_API_KEY: ${{ secrets.HASH_NODE_API_KEY }}
          HASH_NODE_PUBLICATION_ID: ${{ secrets.HASH_NODE_PUBLICATION_ID }}
          HASH_NODE_ENDPOINT: ${{ secrets.HASH_NODE_ENDPOINT }}
